### ISSUE TITLE
Getting type error when TimeShift is loaded (via node)

### ISSUE THREAD

**Issue by git2snap** [plaa/TimeShift-js#8]
I get the following type error when i load the module via node:
"OriginalDate is not a function"

I have tested it also with the online demo on npm and i get the same error try it out here:
https://tonicdev.com/57a1a922d3d2381300d8a820/57a1a922d3d2381300d8a821

It seems that root which is this don't can find the Date constructor.
I also don't understand the export strategy of the module. It don't seems to used the default node way. 

I suggest i just have to call require("timeshift-js") and TimeShift is registered on the global scope. Is this right? Maybe i have to configure something so the inner this can reach the constructor!? I don't have find an example for initialization.

**Comment by Nicd** [comment]
I fixed this by changing `root.Date` to `global.Date` and it seems to work, at least in my case. `root` has been deprecated in Node v6.

**Comment by plaa** [comment]
Should be fixed by #9, now merged and published.
